version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-idea-vmlc-allinone-dev

    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install

  kube-deploy-files: "allinone-idea-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "allinone-idea-vmlc-docker-compose.yaml"
