version: smartide/v0.2
orchestrator:
  type: k8s
  version: 3
workspace:
  dev-container:
    service-name: boathouse-calculator-dev
    ports: # 申明端口
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: vscode  #vscode/theia
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install
  kube-deploy-files: "k8s-vmlc-deployment.yaml" 
