version: "3"
services:
  smartide-vscode-allinone-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-allinone-v2-vscode:latest
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123
      MARKETPLACE_URL: https://marketplace.smartide.cn
    volumes:
      - .:/home/project
    ports:
      - 6822:22
      - 6800:3000
      - 3001:3001
    networks:
      - smartide-network  

networks:
  smartide-network:
    external: true
