
version: "3"
services:
  boathouse-calculator-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-vscode:all-version
    #image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-vscode:latest
    imagePullPolicy: Always
    restart: always
    environment:
      ROOT_PASSWORD: root123
      LOCAL_USER_PASSWORD: root123       
    volumes:
    - .:/home/project
    ports:
      - 3001:3001
      - 6822:22
      - 6800:3000
    networks:
      - smartide-network

networks:
  smartide-network:
    external: true