---

apiVersion: v1
kind: Pod
metadata:
  name: boathouse-calculator-pod
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    boathouse-calculator.service: boathouse-calculator
spec:
  runtimeClassName: sysbox-runc
  containers:
    - env:
        - name: LOCAL_USER_PASSWORD
          value: root123
        - name: MARKETPLACE_URL
          value: https://marketplace.smartide.cn
      name: boathouse-calculator-dev
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vscode-vmlc:all-version
      command: ["/sbin/init"]
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: boathouse-calculator-dev
spec:
  ports:   
    - name: "6800"
      port: 6800
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-allinone.service: boathouse-calculator
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: boathouse-calculator-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              boathouse-calculator/smartide-network: "true"
  podSelector:
    matchLabels:
      boathouse-calculator/smartide-network: "true"
